recipes/default.rb, templates/default/child_ds.json.erb, templates/default/child_pr.json.erb, templates/default/dataset.json.erb, templates/default/parent.json.erb, templates/default/start-river.sh.erb
The was some typos and mistakes in the json files for the rivers. Also one log directory is used now "logs" instead of two "log, logs".
=> fixed bugs in the rivers

Berksfile, attributes/default.rb, metadata.rb, providers/start.rb, recipes/install.rb, recipes/purge.rb, release.sh, templates/default/elasticsearch-start.sh.erb, templates/default/elasticsearch-stop.sh.erb, templates/default/elasticsearch.erb, templates/default/elasticsearch.yml.erb, templates/default/river-start.sh.erb, templates/default/river-stop.sh.erb, templates/default/river.erb, templates/default/start-river.sh.erb, templates/default/stop-river.sh.erb, templates/default/test.sh.erb
dependent cb renamed to apache_hadoop
=> Apache hadoop

recipes/default.rb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-555
=> [HOPSWORKS-555] restart elastic on upgrade

attributes/default.rb, templates/default/elasticsearch.yml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-714
=> [HOPSWORKS-714] elastic config fix

providers/start.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-916
=> [HOPSWORKS-916]  Create index template for kagent

providers/start.rb
Beam job server and sdkworker templates
=> [HOPSWORKS-640]  Flink/Beam

recipes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1331
=> [HOPSWORKS-1331] Consistent flag for system upgrades

recipes/default.rb, templates/default/elastic_exporter.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1457
=> [HOPSWORKS-1457] fix systemd script

templates/default/roles.yml.erb
https://github.com/logicalclocks/hops-testing/pull/567
tests: https://github.com/logicalclocks/hops-testing/pull/567
=> [HOPSWORKS-1476] Add support for elasticsearch spark connector

libraries/elastic_helpers.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1509
=> [HOPSWORKS-1509] Allow all OU in nodes DN in elasticsearch configuration

libraries/elastic_helpers.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1306
tests: https://github.com/logicalclocks/hops-testing/pull/603
=> [HOPSWORKS-1306][ePipe] Add support for HA Elasticsearch

attributes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1528
tests: https://github.com/logicalclocks/hops-testing/pull/597
=> [HOPSWORKS-1528] Remove unnecessary code to set kibana default index

recipes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1561
tests: https://github.com/logicalclocks/hops-testing/pull/623
=> [HOPSWORKS-1561] Restrict access to elasticsearch data directory to elastic user

attributes/default.rb, providers/start.rb, templates/default/roles.yml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1667
=> [HOPSWORKS-1667] featurestore index

attributes/default.rb, metadata.rb, providers/start.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1770
=> [HOPSWORKS-1770] reindex featurestore index

Berksfile, recipes/default.rb
tests: https://github.com/logicalclocks/hops-testing-ee/pull/110
=> [HOPSWORKS-1862] Fix cyclic dependency error

attributes/default.rb, libraries/elastic_helpers.rb, metadata.rb, providers/opendistro.rb, recipes/default.rb, recipes/install.rb, templates/default/elastic_exporter.service.erb, templates/default/run_securityAdmin.sh.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1657
=> [HOPSWORKS-1657] System users x.509 v2

libraries/elastic_helpers.rb, recipes/default.rb
tests on 1.4: https://github.com/logicalclocks/hops-testing-ee/pull/112
=> [HOPSWORKS-1871] Add admin DNs to all elasticsearch nodes

providers/opendistro.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1977
=> [HOPSWORKS-1977] Replace kagent/test with kagent/enabled

templates/default/elasticsearch.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
=> [HOPSWORKS-2065] Automatically restart failed systemd units

templates/default/elasticsearch.service.erb
* [HOPSWORKS-2065] Automatically restart failed systemd units
* [HOPSWORKS-2065] Fix burst
[HOPSWORKS-2065]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
[HOPSWORKS-2065]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
=> [HOPSWORKS-2065] Automatically restart failed systemd units (#51)

attributes/default.rb, recipes/default.rb
[HOPSWORKS-2578] Rename
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2578
[HOPSWORKS-2578]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2578
=> [HOPSWORKS-2578] Create elasticsearch data_dir under data dir

attributes/default.rb, providers/start.rb, templates/default/reindex-base-indices.sh.erb
Fixes https://github.com/logicalclocks/hopsworks-cloud/issues/1833
=> [HOPSWORKS-CLOUD-1833] Add a script to reindex base indices

recipes/default.rb
https://hopsworks.atlassian.net/browse/HOPSWORKS-2763
=> [HOPSWORKS-2763][APPEND] opensearch

recipes/default.rb
https://hopsworks.atlassian.net/browse/HWORKS-297
=> [HWORKS-297] Retry package resource

providers/start.rb
https://hopsworks.atlassian.net/browse/CLOUD-175
=> [CLOUD-175] Update services template to include rondb properties

Berksfile, Karamelfile, attributes/default.rb, metadata.rb, providers/start.rb, recipes/default.rb, recipes/install_repository.rb, recipes/install_s3_repository.rb, recipes/register_s3_repository.rb, recipes/restore_snapshot.rb, resources/start.rb, templates/default/opensearch.yml.erb, templates/default/snapshot_indices.sh.erb
[CLOUD-393] Register an S3 snapshot repository
[CLOUD-393] Snapshot indices script
[CLOUD-393] Restore indices snapshot
[CLOUD-393] Expose attribute to set indices to snapshot
[CLOUD-393]: https://hopsworks.atlassian.net/browse/CLOUD-393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CLOUD-393]: https://hopsworks.atlassian.net/browse/CLOUD-393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CLOUD-393]: https://hopsworks.atlassian.net/browse/CLOUD-393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CLOUD-393]: https://hopsworks.atlassian.net/browse/CLOUD-393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CLOUD-393] Snapshot and restore file and app provenances indices
